// ignore_for_file: camel_case_types

class cardModel {
  final String cardHoldername;
  final String cardNumber;
  final String expiryDate;
  final String cardType;
  final String method;
  final String cardLogo;
  final String cardImage;
  final List<double> graphItems;
  final String percentages;
  final int receiveAmount;

  cardModel(
      {required this.cardHoldername,
      required this.cardNumber,
      required this.expiryDate,
      required this.cardType,
      required this.method,
      required this.cardLogo,
      required this.cardImage,
      required this.percentages,
      required this.receiveAmount,
      required this.graphItems});
}

final List<cardModel> cards = [
  cardModel(
    cardHoldername: 'Agyapong Rendosland',
    cardNumber: '12 / 24',
    expiryDate: "3.10",
    cardType: 'Debit Card',
    method: 'images/pexels.jpg',
    cardLogo: 'images/pexels.jpg',
    cardImage: 'images/pexels.jpg',
    percentages: '30',
    receiveAmount: 152,
    graphItems: const <double>[
      2,
      1,
      11,
      25,
      17,
      30,
      24,
      70,
      35,
      55,
      33,
      43,
      6,
      8,
      7,
      10,
      30,
      5,
      10,
      23,
      50,
      70,
      50,
      55,
      20,
      40,
      42,
      60,
      80,
      75,
      90,
    ],
  ),
  cardModel(
    cardHoldername: 'Agyapong Rendosland',
    cardNumber: '12 / 24',
    expiryDate: "3.10",
    cardType: 'Debit Card',
    method: 'images/pexels.jpg',
    cardLogo: 'images/pexels.jpg',
    cardImage: 'images/pexels.jpg',
    percentages: '30',
    receiveAmount: 152,
    graphItems: const <double>[
      2,
      1,
      11,
      25,
      17,
      30,
      24,
      70,
      35,
      55,
      33,
      43,
      6,
      8,
      7,
      10,
      30,
      5,
      10,
      23,
      50,
      70,
      50,
      55,
      20,
      40,
      42,
      60,
      80,
      75,
      90,
    ],
  ),
  cardModel(
    cardHoldername: 'Agyapong Rendosland',
    cardNumber: '12 / 24',
    expiryDate: "3.10",
    cardType: 'Debit Card',
    method: 'images/pexels.jpg',
    cardLogo: 'images/pexels.jpg',
    cardImage: 'images/pexels.jpg',
    percentages: '30',
    receiveAmount: 152,
    graphItems: const <double>[
      2,
      1,
      11,
      25,
      17,
      30,
      24,
      70,
      35,
      55,
      33,
      43,
      6,
      8,
      7,
      10,
      30,
      5,
      10,
      23,
      50,
      70,
      50,
      55,
      20,
      40,
      42,
      60,
      80,
      75,
      90,
    ],
  ),
  cardModel(
    cardHoldername: 'Agyapong Rendosland',
    cardNumber: '12 / 24',
    expiryDate: "3.10",
    cardType: 'Debit Card',
    method: 'images/pexels.jpg',
    cardLogo: 'images/pexels.jpg',
    cardImage: 'images/pexels.jpg',
    percentages: '30',
    receiveAmount: 152,
    graphItems: const <double>[
      2,
      1,
      11,
      25,
      17,
      30,
      24,
      70,
      35,
      55,
      33,
      43,
      6,
      8,
      7,
      10,
      30,
      5,
      10,
      23,
      50,
      70,
      50,
      55,
      20,
      40,
      42,
      60,
      80,
      75,
      90,
    ],
  ),
];
